import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "@/components/footer";
import Chatbot from "@/components/chatbot";
import SessionWrapper from "@/components/SessionWrapper";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "FashionMart",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <SessionWrapper>
        {children}
        <Chatbot/>
        <Footer/>
      </SessionWrapper>
        </body>
    </html>
  );
}
